# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/io.xdc

# IP: ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet
